# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - 3.5.0
sudo: false
cache: packages

before_install:
  - sudo mkdir -p /usr/lib/R/library
  - echo 'R_LIBS=/usr/lib/R/library:/usr/lib/R/site-library/' > ~/.Renviron
  - sudo chmod 2777 /usr/lib/R/library

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
